$(document).ready(function(){
    $("strong:contains('SÅLD')").addClass('reserved');
    $("strong:contains('RESERVERAD')").addClass('reserved');
    $("strong:contains('RESERVED')").addClass('reserved');
    $("strong:contains('TINGAD')").addClass('reserved');
    $("strong:contains('BOOKED')").addClass('reserved');
    $("strong:contains('TILLGÄNGLIG')").addClass('reserved');
    $("strong:contains('AVAILABLE')").addClass('reserved');
    $("strong:contains('SOLD')").addClass('reserved');
});